site_name: iGEM 2025 Documentation
# site_url: https://your-team.igem.wiki/
repo_name: DocuGuideline
repo_url: https://github.com/AnyaReese/DocuGuideline/
edit_uri: tree/master/docs
copyright: Copyright &copy; 2025 AnyaReese; 2023 TonyCrane with CC BY-SA 4.0

nav:
  - 首页: index.md
  - 写作指南:
    - 格式规范:
      # - 中英混排规范: guide/format/mixed.md
      # - 标点符号使用: guide/format/punctuation.md 
      - 排版建议: guide/format/layout.md
    - 内容规范:
      - 各种格式编写: guide/content/references.md
      # - 术语表: guide/content/glossary.md
      # - 图表制作: guide/content/figures.md
  - 湿队项目协作:
    - 项目概述: project/overview.md 
      # - 实验方法: project/methods.md
      # - 实验结果: project/results.md
      # - 讨论: project/discussion.md

theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - content.code.annotate
  font:
    text: Roboto
    code: JetBrains Mono
  palette:
    - scheme: default

plugins:
  - search
  - statistics
  - heti:
      extra_skipped_class:
        - arithmatex
      disable_serve: false

extra_javascript:
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - js/katex.js

extra_css:
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://fonts.googleapis.com/css?family=Roboto:500,500i,600,600i&display=fallback
  - css/custom.css
  - css/scheme.css

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
