site_name: 实验文档降压宝典
site_url: https://hypotensor.tonycrane.cc/
repo_name: lab-hypotensor
repo_url: https://github.com/TonyCrane/lab-hypotensor/
edit_uri: tree/master/docs
copyright: Copyright &copy; 2023 TonyCrane with CC BY-SA 4.0

nav:
  - 首页: index.md
  - 助教版:
    - ta/index.md
    - 重修 markdown！:
      - ta/markdown/index.md
      - 常见错误用法集锦: ta/markdown/syntax.md
      - 其他编写建议: ta/markdown/suggestions.md
    - 去读各个文档！:
      - ta/rtfm/index.md
      - mkdocs 配置拾遗: ta/rtfm/mkdocs.md
      - material 主题使用拾遗: ta/rtfm/material.md
      - markdown 扩展配置拾遗: ta/rtfm/markdown.md
    - 多少学点排版:
      - ta/typesetting/index.md
      - 标点符号的使用: ta/typesetting/punctuation.md
      - 更多排版建议: ta/typesetting/suggestions.md
  - 学生版:
    - stu/index.md

theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.action.edit
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.expand
  font:
    code: JetBrains Mono
  palette:
    - scheme: default

plugins:
  - search
  - statistics
  - heti:
      extra_skipped_class:
        - arithmatex
      disable_serve: false

extra_javascript:
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - js/katex.js

extra_css:
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://fonts.googleapis.com/css?family=Roboto:500,500i,600,600i&display=fallback
  - css/custom.css
  - css/scheme.css

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
